on: [push, pull_request]
name: ci
jobs:
  linux-ci:
    name: linux-${{ matrix.name }}
    runs-on: ubuntu-20.04

    strategy:
      fail-fast: false
      matrix:
        include:
          - name: clang-12
            compiler: clang
            version: 12

    steps:
    - name: Set up gcc env
      if: startsWith(matrix.compiler, 'gcc')
      run: |
        echo "CC=gcc-${{ matrix.version }}" >> $GITHUB_ENV
        echo "CXX=g++-${{ matrix.version }}" >> $GITHUB_ENV
    - name: Set up clang env
      if: startsWith(matrix.compiler, 'clang')
      run: |
        echo "CC=clang-${{ matrix.version }}" >> $GITHUB_ENV
        echo "CXX=clang++-${{ matrix.version }}" >> $GITHUB_ENV
    - uses: actions/checkout@v3
    - name: Build and test
      run: bazel test ...

  windows-msvc:
    runs-on: windows-2022
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v3
    - name: Build and test
      run: bazel test ...

  linux-gcc-10-coverage:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Coverage
      run: CC=gcc-10 CXX=g++-10 bazel coverage --combined_report=lcov ...
    - name: Upload
      run: bash <(curl -s https://codecov.io/bash) -f bazel-out/_coverage/_coverage_report.dat

  buildifier:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v3
    - name: Install
      run: |
        wget --output-document=buildifier https://github.com/bazelbuild/buildtools/releases/download/5.1.0/buildifier-linux-amd64
        sudo chmod +x buildifier
    - name: Check
      run: ./buildifier --lint=warn --warnings=all -mode diff WORKSPACE $(find . -type f -iname "*.BUILD" -or -iname BUILD)
